blank_issues_enabled: false
contact_links:
  - name: 📚 GitHub Community Discussions
    url: https://github.com/carlosferreyra/discussions
    about: Please ask and answer questions here.
  - name: 📖 Documentation
    url: https://github.com/carlosferreyra/docs
    about: Check our documentation before opening an issue.
  - name: 💬 Join the Community
    url: https://github.com/carlosferreyra/community
    about: Connect with other users and contributors.
