title: GitHub Repository Templates
description: Practical guidance for default GitHub community health files and templates.
theme: minima
repository: carlosferreyra/.github
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
header_pages:
  - inheritance.md
  - community-health-files.md
  - issue-templates.md
  - pull-request-template.md
  - discussion-templates.md
  - repository-operations.md
